<!-- above link set pending -->
<div>
    <div class="column-2 women-catalog-slider" style="margin-top: -1%; font-family: 'Oswald', sans-serif;">
         <?php
            echo $this->getLayout()
              ->createBlock('Magento\Cms\Block\Block')
              ->setBlockId('women-s')
              ->toHtml();
          ?>
    </div>
</div>
<div style="width:100%; float:left; font-family: 'Oswald', sans-serif;" > 
    <div>
        <?php
            echo $this->getLayout()
              ->createBlock('Magento\Cms\Block\Block')
              ->setBlockId('men')
              ->toHtml();
          ?>
         </div>
    </div>
    <!-- <script type="text/javascript" xml="space">
    require([
        'jquery',
        'bxSlider'
    ], function ($) {
        'use strict';
        // $.noConflict();

    
            $('.cake').bxSlider({
                // controls: true,
                captions: true,
                slideWidth: 200,
                minSlides:3,
                maxSlides:3,
                moveSlides:3
            });
        });
    });

</script> -->

<script type="text/javascript" xml="space">
    require([
        'jquery',
        'bxSlider'
    ], function($){
        $(document).ready(function() {
            $('.cake-silder').bxSlider( {
                controls: true,
                captions: true,
                slideWidth: 200,  
                minSlides:3,
                maxSlides:3,
                moveSlides:3
            });
        });
    });
</script>

<!-- 
<script type="text/javascript" xml="space">
    require([
        'jquery',
        'bxSlider'
    ], function ($) {
        // 'use strict';
        // $.noConflict();

        //less-essential-slider
        $(document).ready(function() {
            $('.cake').bxSlider( {
                // controls: true,
                captions: true,
                slideWidth: 200,
                minSlides:3,
                maxSlides:3,
                moveSlides:3
            });
        });

        //men-catalog-carousel
        // $(document).ready(function() {
        //     $('.bxslider').bxSlider( {
        //         // controls: true,
        //         captions: true,
        //         minSlides:3,
        //         maxSlides:3,
        //         moveSlides:3,
        //         slideWidth: 200
        //     });
        // });
    });
</script> -->
